const compMap = {
  Div: {
    name: "Div",
    title: "层标签",
    icon: "tuceng",
    dependence: {
      package: "@ali/iceluna-comp-div",
      export_name: "Div",
      sub_name: "",
      destructuring: 0,
      main: "",
    },
    dependenceVersion: "1.0.0",
    category: "默认",
    libraryId: -1,
    isShow: true,
    isContainer: 1,
    props: [],
    remarkProp: "className",
  },
  Text: {
    name: "Text",
    title: "文本",
    icon: "wenben",
    category: "默认",
    dependence: {
      package: "@ali/iceluna-comp-text",
      export_name: "Text",
      sub_name: "",
      destructuring: 0,
      main: "",
    },
    dependenceVersion: "1.0.0",
    libraryId: -1,
    isShow: true,
    isContainer: 0,
    remarkProp: "className",
    props: [
      {
        category: "基础属性",
        label: "文本内容",
        name: "text",
        type: "Mixin",
        props: '{"types":["Input","Expression"],"defaultType":"Input"}',
        extra: {
          propType: "PropTypes.oneOfType([PropTypes.string, PropTypes.number])",
        },
      },
    ],
  },
  Image: {
    name: "Image",
    title: "图片",
    icon: "picture",
    category: "展示",
    libraryId: -1,
    isShow: true,
    isContainer: 0,
    remarkProp: "className",
    dependence: {
      package: "@ali/iceluna-comp-image",
      export_name: "Image",
      sub_name: "",
      destructuring: 0,
      main: "",
    },
    dependenceVersion: "1.0.0",
    props:
      '[{"category":"基础属性","label":"图片地址","name":"src","type":"Mixin","props":{"types":["Input","Expression"],"defaultType":"Input"}},{"category":"基础属性","label":"图片标题","name":"title","type":"Mixin","props":{"types":["Input","Expression"],"defaultType":"Input"}}]',
  },
  Block: {
    name: "Block",
    title: "区块容器",
    icon: "jihe",
    category: "默认",
    libraryId: -1,
    isShow: true,
    isContainer: 1,
    dependence: {
      package: "",
      export_name: "",
      sub_name: "",
      destructuring: 0,
      main: "",
    },
    props:
      '[{"category":"基础属性","label":"文件名称","name":"__fileName","type":"Mixin","props":{"types":["Input","Expression"],"defaultType":"Input"}}]',
  },
  Component: {
    name: "Component",
    title: "组件容器",
    icon: "jihe",
    category: "默认",
    libraryId: -1,
    isShow: true,
    isContainer: 1,
    dependence: {
      package: "",
      export_name: "",
      sub_name: "",
      destructuring: 0,
      main: "",
    },
    props:
      '[{"category":"基础属性","label":"文件名称","name":"__fileName","type":"Mixin","props":{"types":["Input","Expression"],"defaultType":"Input"}}]',
  },
  Page: {
    name: "Page",
    title: "页面容器",
    description: "页面容器，用于包裹整个页面，提供页面范围的数据容器",
    icon: "shitu",
    category: "默认",
    libraryId: -1,
    isShow: true,
    isContainer: 1,
    dependence: {
      package: "",
      export_name: "",
      sub_name: "",
      destructuring: 0,
      main: "",
    },
  },
  Button: {
    name: "Button",
    title: "按钮",
    screenshot: "",
    icon: null,
    tags: null,
    package: "element-plus",
    destructuring: 1,
    description: null,
    dependence: {
      package: "element-plus",
      export_name: "ElButton",
      sub_name: null,
      destructuring: 1,
    },
    props: null,
    version: "*",
    code: "",
    basicId: 1096,
    versionId: 1270,
    isContainer: 0,
    isLayout: 0,
    parentRule: null,
    childrenRule: null,
    remarkProp: null,
    exportName: "ElButton",
    subName: null,
    isShow: 1,
    devMode: 1,
    isOpen: 0,
    docLink: null,
    docDetail: null,
    dependenceVersion: "*",
    items: [],
    libraryId: 978,
  },
  Input: {
    name: "Input",
    title: "输入框",
    screenshot: "",
    icon: null,
    tags: null,
    package: "element-plus",
    destructuring: 1,
    description: null,
    dependence: {
      package: "element-plus",
      export_name: "ElInput",
      sub_name: null,
      destructuring: 1,
    },
    props: null,
    version: "*",
    code: "",
    basicId: 1097,
    versionId: 1271,
    isContainer: 0,
    isLayout: 0,
    parentRule: null,
    childrenRule: null,
    remarkProp: null,
    exportName: "ElInput",
    subName: null,
    isShow: 1,
    devMode: 1,
    isOpen: 0,
    docLink: null,
    docDetail: null,
    dependenceVersion: "*",
    items: [],
    libraryId: 978,
  },
};

module.exports = {
  list: Object.keys(compMap).map(v => compMap[v])
}